// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// VCSConnectionServiceClient is the client API for VCSConnectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VCSConnectionServiceClient interface {
	//internal
	GetVCSConnection(ctx context.Context, in *GetVCSConnectionRequest, opts ...grpc.CallOption) (*VCSConnection, error)
	CreateVCSConnection(ctx context.Context, in *CreateVCSConnectionRequest, opts ...grpc.CallOption) (*VCSConnection, error)
	RevokeVCSToken(ctx context.Context, in *RevokeVCSTokenRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	RenewVCSToken(ctx context.Context, in *RenewVCSTokenRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type vCSConnectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVCSConnectionServiceClient(cc grpc.ClientConnInterface) VCSConnectionServiceClient {
	return &vCSConnectionServiceClient{cc}
}

func (c *vCSConnectionServiceClient) GetVCSConnection(ctx context.Context, in *GetVCSConnectionRequest, opts ...grpc.CallOption) (*VCSConnection, error) {
	out := new(VCSConnection)
	err := c.cc.Invoke(ctx, "/pb.VCSConnectionService/GetVCSConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vCSConnectionServiceClient) CreateVCSConnection(ctx context.Context, in *CreateVCSConnectionRequest, opts ...grpc.CallOption) (*VCSConnection, error) {
	out := new(VCSConnection)
	err := c.cc.Invoke(ctx, "/pb.VCSConnectionService/CreateVCSConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vCSConnectionServiceClient) RevokeVCSToken(ctx context.Context, in *RevokeVCSTokenRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.VCSConnectionService/RevokeVCSToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vCSConnectionServiceClient) RenewVCSToken(ctx context.Context, in *RenewVCSTokenRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.VCSConnectionService/RenewVCSToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VCSConnectionServiceServer is the server API for VCSConnectionService service.
// All implementations must embed UnimplementedVCSConnectionServiceServer
// for forward compatibility
type VCSConnectionServiceServer interface {
	//internal
	GetVCSConnection(context.Context, *GetVCSConnectionRequest) (*VCSConnection, error)
	CreateVCSConnection(context.Context, *CreateVCSConnectionRequest) (*VCSConnection, error)
	RevokeVCSToken(context.Context, *RevokeVCSTokenRequest) (*empty.Empty, error)
	RenewVCSToken(context.Context, *RenewVCSTokenRequest) (*empty.Empty, error)
	//mustEmbedUnimplementedVCSConnectionServiceServer()
}

// UnimplementedVCSConnectionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVCSConnectionServiceServer struct {
}

func (UnimplementedVCSConnectionServiceServer) GetVCSConnection(context.Context, *GetVCSConnectionRequest) (*VCSConnection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVCSConnection not implemented")
}
func (UnimplementedVCSConnectionServiceServer) CreateVCSConnection(context.Context, *CreateVCSConnectionRequest) (*VCSConnection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVCSConnection not implemented")
}
func (UnimplementedVCSConnectionServiceServer) RevokeVCSToken(context.Context, *RevokeVCSTokenRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeVCSToken not implemented")
}
func (UnimplementedVCSConnectionServiceServer) RenewVCSToken(context.Context, *RenewVCSTokenRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewVCSToken not implemented")
}
func (UnimplementedVCSConnectionServiceServer) mustEmbedUnimplementedVCSConnectionServiceServer() {}

// UnsafeVCSConnectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VCSConnectionServiceServer will
// result in compilation errors.
type UnsafeVCSConnectionServiceServer interface {
	mustEmbedUnimplementedVCSConnectionServiceServer()
}

func RegisterVCSConnectionServiceServer(s *grpc.Server, srv VCSConnectionServiceServer) {
	s.RegisterService(&_VCSConnectionService_serviceDesc, srv)
}

func _VCSConnectionService_GetVCSConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVCSConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCSConnectionServiceServer).GetVCSConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VCSConnectionService/GetVCSConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCSConnectionServiceServer).GetVCSConnection(ctx, req.(*GetVCSConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VCSConnectionService_CreateVCSConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVCSConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCSConnectionServiceServer).CreateVCSConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VCSConnectionService/CreateVCSConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCSConnectionServiceServer).CreateVCSConnection(ctx, req.(*CreateVCSConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VCSConnectionService_RevokeVCSToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeVCSTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCSConnectionServiceServer).RevokeVCSToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VCSConnectionService/RevokeVCSToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCSConnectionServiceServer).RevokeVCSToken(ctx, req.(*RevokeVCSTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VCSConnectionService_RenewVCSToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewVCSTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VCSConnectionServiceServer).RenewVCSToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VCSConnectionService/RenewVCSToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VCSConnectionServiceServer).RenewVCSToken(ctx, req.(*RenewVCSTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VCSConnectionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.VCSConnectionService",
	HandlerType: (*VCSConnectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVCSConnection",
			Handler:    _VCSConnectionService_GetVCSConnection_Handler,
		},
		{
			MethodName: "CreateVCSConnection",
			Handler:    _VCSConnectionService_CreateVCSConnection_Handler,
		},
		{
			MethodName: "RevokeVCSToken",
			Handler:    _VCSConnectionService_RevokeVCSToken_Handler,
		},
		{
			MethodName: "RenewVCSToken",
			Handler:    _VCSConnectionService_RenewVCSToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vcs-connection-service.proto",
}
