// Code generated by proroc-gen-graphql, DO NOT EDIT.
package pb

import (
	"github.com/graphql-go/graphql"
	gql_ptypes_timestamp "github.com/ysugimoto/grpc-graphql-gateway/ptypes/timestamp"
)

var (
	gql__enum_VCSConnectionProvider            *graphql.Enum        // enum VCSConnectionProvider in vcs-connection-service.proto
	gql__type_VCSConnection                    *graphql.Object      // message VCSConnection in vcs-connection-service.proto
	gql__type_RevokeVCSTokenRequest            *graphql.Object      // message RevokeVCSTokenRequest in vcs-connection-service.proto
	gql__type_RenewVCSTokenRequest             *graphql.Object      // message RenewVCSTokenRequest in vcs-connection-service.proto
	gql__type_ListVCSConnectionResponse        *graphql.Object      // message ListVCSConnectionResponse in vcs-connection-service.proto
	gql__type_ListVCSConnectionRequest         *graphql.Object      // message ListVCSConnectionRequest in vcs-connection-service.proto
	gql__type_ListAlfredVCSConnectionResponse  *graphql.Object      // message ListAlfredVCSConnectionResponse in vcs-connection-service.proto
	gql__type_ConnectedRequest                 *graphql.Object      // message ConnectedRequest in vcs-connection-service.proto
	gql__type_ConnectResponse                  *graphql.Object      // message ConnectResponse in vcs-connection-service.proto
	gql__type_ConnectRequest                   *graphql.Object      // message ConnectRequest in vcs-connection-service.proto
	gql__type_AccountVCSConnection             *graphql.Object      // message AccountVCSConnection in vcs-connection-service.proto
	gql__input_VCSConnection                   *graphql.InputObject // message VCSConnection in vcs-connection-service.proto
	gql__input_RevokeVCSTokenRequest           *graphql.InputObject // message RevokeVCSTokenRequest in vcs-connection-service.proto
	gql__input_RenewVCSTokenRequest            *graphql.InputObject // message RenewVCSTokenRequest in vcs-connection-service.proto
	gql__input_ListVCSConnectionResponse       *graphql.InputObject // message ListVCSConnectionResponse in vcs-connection-service.proto
	gql__input_ListVCSConnectionRequest        *graphql.InputObject // message ListVCSConnectionRequest in vcs-connection-service.proto
	gql__input_ListAlfredVCSConnectionResponse *graphql.InputObject // message ListAlfredVCSConnectionResponse in vcs-connection-service.proto
	gql__input_ConnectedRequest                *graphql.InputObject // message ConnectedRequest in vcs-connection-service.proto
	gql__input_ConnectResponse                 *graphql.InputObject // message ConnectResponse in vcs-connection-service.proto
	gql__input_ConnectRequest                  *graphql.InputObject // message ConnectRequest in vcs-connection-service.proto
	gql__input_AccountVCSConnection            *graphql.InputObject // message AccountVCSConnection in vcs-connection-service.proto
)

func Gql__enum_VCSConnectionProvider() *graphql.Enum {
	if gql__enum_VCSConnectionProvider == nil {
		gql__enum_VCSConnectionProvider = graphql.NewEnum(graphql.EnumConfig{
			Name: "Pb_Enum_VCSConnectionProvider",
			Values: graphql.EnumValueConfigMap{
				"VCS_UNKNOWN": &graphql.EnumValueConfig{
					Value: VCSConnectionProvider(0),
				},
				"VCS_GITHUB": &graphql.EnumValueConfig{
					Value: VCSConnectionProvider(1),
				},
				"VCS_GITLAB": &graphql.EnumValueConfig{
					Value: VCSConnectionProvider(2),
				},
				"VCS_BITBUCKET": &graphql.EnumValueConfig{
					Value: VCSConnectionProvider(3),
				},
			},
		})
	}
	return gql__enum_VCSConnectionProvider
}

func Gql__type_VCSConnection() *graphql.Object {
	if gql__type_VCSConnection == nil {
		gql__type_VCSConnection = graphql.NewObject(graphql.ObjectConfig{
			Name: "Pb_Type_VCSConnection",
			Fields: graphql.Fields{
				"id": &graphql.Field{
					Type:        graphql.String,
					Description: `id generated by uuid`,
				},
				"provider": &graphql.Field{
					Type: Gql__enum_VCSConnectionProvider(),
				},
				"connection_id": &graphql.Field{
					Type: graphql.String,
				},
				"accessToken": &graphql.Field{
					Type: graphql.String,
				},
				"refreshToken": &graphql.Field{
					Type: graphql.String,
				},
				"accessTokenExpiry": &graphql.Field{
					Type: gql_ptypes_timestamp.Gql__type_Timestamp(),
				},
				"refreshTokenExpiry": &graphql.Field{
					Type: gql_ptypes_timestamp.Gql__type_Timestamp(),
				},
				"revoked": &graphql.Field{
					Type: graphql.Boolean,
				},
				"account_id": &graphql.Field{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__type_VCSConnection
}

func Gql__type_RevokeVCSTokenRequest() *graphql.Object {
	if gql__type_RevokeVCSTokenRequest == nil {
		gql__type_RevokeVCSTokenRequest = graphql.NewObject(graphql.ObjectConfig{
			Name: "Pb_Type_RevokeVCSTokenRequest",
			Fields: graphql.Fields{
				"provider": &graphql.Field{
					Type: Gql__enum_VCSConnectionProvider(),
				},
				"vcs_id": &graphql.Field{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__type_RevokeVCSTokenRequest
}

func Gql__type_RenewVCSTokenRequest() *graphql.Object {
	if gql__type_RenewVCSTokenRequest == nil {
		gql__type_RenewVCSTokenRequest = graphql.NewObject(graphql.ObjectConfig{
			Name: "Pb_Type_RenewVCSTokenRequest",
			Fields: graphql.Fields{
				"provider": &graphql.Field{
					Type: Gql__enum_VCSConnectionProvider(),
				},
			},
		})
	}
	return gql__type_RenewVCSTokenRequest
}

func Gql__type_ListVCSConnectionResponse() *graphql.Object {
	if gql__type_ListVCSConnectionResponse == nil {
		gql__type_ListVCSConnectionResponse = graphql.NewObject(graphql.ObjectConfig{
			Name: "Pb_Type_ListVCSConnectionResponse",
			Fields: graphql.Fields{
				"vcs_connection": &graphql.Field{
					Type: graphql.NewList(Gql__type_AccountVCSConnection()),
				},
			},
		})
	}
	return gql__type_ListVCSConnectionResponse
}

func Gql__type_ListVCSConnectionRequest() *graphql.Object {
	if gql__type_ListVCSConnectionRequest == nil {
		gql__type_ListVCSConnectionRequest = graphql.NewObject(graphql.ObjectConfig{
			Name: "Pb_Type_ListVCSConnectionRequest",
			Fields: graphql.Fields{
				"account_id": &graphql.Field{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__type_ListVCSConnectionRequest
}

func Gql__type_ListAlfredVCSConnectionResponse() *graphql.Object {
	if gql__type_ListAlfredVCSConnectionResponse == nil {
		gql__type_ListAlfredVCSConnectionResponse = graphql.NewObject(graphql.ObjectConfig{
			Name: "Pb_Type_ListAlfredVCSConnectionResponse",
			Fields: graphql.Fields{
				"providers": &graphql.Field{
					Type: graphql.NewList(graphql.String),
				},
			},
		})
	}
	return gql__type_ListAlfredVCSConnectionResponse
}

func Gql__type_ConnectedRequest() *graphql.Object {
	if gql__type_ConnectedRequest == nil {
		gql__type_ConnectedRequest = graphql.NewObject(graphql.ObjectConfig{
			Name: "Pb_Type_ConnectedRequest",
			Fields: graphql.Fields{
				"provider": &graphql.Field{
					Type: Gql__enum_VCSConnectionProvider(),
				},
				"state": &graphql.Field{
					Type: graphql.String,
				},
				"code": &graphql.Field{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__type_ConnectedRequest
}

func Gql__type_ConnectResponse() *graphql.Object {
	if gql__type_ConnectResponse == nil {
		gql__type_ConnectResponse = graphql.NewObject(graphql.ObjectConfig{
			Name: "Pb_Type_ConnectResponse",
			Fields: graphql.Fields{
				"uri": &graphql.Field{
					Type: graphql.String,
				},
				"account_id": &graphql.Field{
					Type: graphql.String,
				},
				"user_id": &graphql.Field{
					Type: graphql.String,
				},
				"temp_jwt_token": &graphql.Field{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__type_ConnectResponse
}

func Gql__type_ConnectRequest() *graphql.Object {
	if gql__type_ConnectRequest == nil {
		gql__type_ConnectRequest = graphql.NewObject(graphql.ObjectConfig{
			Name: "Pb_Type_ConnectRequest",
			Fields: graphql.Fields{
				"provider": &graphql.Field{
					Type: Gql__enum_VCSConnectionProvider(),
				},
			},
		})
	}
	return gql__type_ConnectRequest
}

func Gql__type_AccountVCSConnection() *graphql.Object {
	if gql__type_AccountVCSConnection == nil {
		gql__type_AccountVCSConnection = graphql.NewObject(graphql.ObjectConfig{
			Name: "Pb_Type_AccountVCSConnection",
			Fields: graphql.Fields{
				"id": &graphql.Field{
					Type: graphql.String,
				},
				"provider": &graphql.Field{
					Type: Gql__enum_VCSConnectionProvider(),
				},
				"account_id": &graphql.Field{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__type_AccountVCSConnection
}

func Gql__input_VCSConnection() *graphql.InputObject {
	if gql__input_VCSConnection == nil {
		gql__input_VCSConnection = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Pb_Input_VCSConnection",
			Fields: graphql.InputObjectConfigFieldMap{
				"id": &graphql.InputObjectFieldConfig{
					Description: `id generated by uuid`,
					Type:        graphql.String,
				},
				"provider": &graphql.InputObjectFieldConfig{
					Type: Gql__enum_VCSConnectionProvider(),
				},
				"connection_id": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"accessToken": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"refreshToken": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"accessTokenExpiry": &graphql.InputObjectFieldConfig{
					Type: gql_ptypes_timestamp.Gql__input_Timestamp(),
				},
				"refreshTokenExpiry": &graphql.InputObjectFieldConfig{
					Type: gql_ptypes_timestamp.Gql__input_Timestamp(),
				},
				"revoked": &graphql.InputObjectFieldConfig{
					Type: graphql.Boolean,
				},
				"account_id": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__input_VCSConnection
}

func Gql__input_RevokeVCSTokenRequest() *graphql.InputObject {
	if gql__input_RevokeVCSTokenRequest == nil {
		gql__input_RevokeVCSTokenRequest = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Pb_Input_RevokeVCSTokenRequest",
			Fields: graphql.InputObjectConfigFieldMap{
				"provider": &graphql.InputObjectFieldConfig{
					Type: Gql__enum_VCSConnectionProvider(),
				},
				"vcs_id": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__input_RevokeVCSTokenRequest
}

func Gql__input_RenewVCSTokenRequest() *graphql.InputObject {
	if gql__input_RenewVCSTokenRequest == nil {
		gql__input_RenewVCSTokenRequest = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Pb_Input_RenewVCSTokenRequest",
			Fields: graphql.InputObjectConfigFieldMap{
				"provider": &graphql.InputObjectFieldConfig{
					Type: Gql__enum_VCSConnectionProvider(),
				},
			},
		})
	}
	return gql__input_RenewVCSTokenRequest
}

func Gql__input_ListVCSConnectionResponse() *graphql.InputObject {
	if gql__input_ListVCSConnectionResponse == nil {
		gql__input_ListVCSConnectionResponse = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Pb_Input_ListVCSConnectionResponse",
			Fields: graphql.InputObjectConfigFieldMap{
				"vcs_connection": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(Gql__input_AccountVCSConnection()),
				},
			},
		})
	}
	return gql__input_ListVCSConnectionResponse
}

func Gql__input_ListVCSConnectionRequest() *graphql.InputObject {
	if gql__input_ListVCSConnectionRequest == nil {
		gql__input_ListVCSConnectionRequest = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Pb_Input_ListVCSConnectionRequest",
			Fields: graphql.InputObjectConfigFieldMap{
				"account_id": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__input_ListVCSConnectionRequest
}

func Gql__input_ListAlfredVCSConnectionResponse() *graphql.InputObject {
	if gql__input_ListAlfredVCSConnectionResponse == nil {
		gql__input_ListAlfredVCSConnectionResponse = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Pb_Input_ListAlfredVCSConnectionResponse",
			Fields: graphql.InputObjectConfigFieldMap{
				"providers": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.String),
				},
			},
		})
	}
	return gql__input_ListAlfredVCSConnectionResponse
}

func Gql__input_ConnectedRequest() *graphql.InputObject {
	if gql__input_ConnectedRequest == nil {
		gql__input_ConnectedRequest = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Pb_Input_ConnectedRequest",
			Fields: graphql.InputObjectConfigFieldMap{
				"provider": &graphql.InputObjectFieldConfig{
					Type: Gql__enum_VCSConnectionProvider(),
				},
				"state": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"code": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__input_ConnectedRequest
}

func Gql__input_ConnectResponse() *graphql.InputObject {
	if gql__input_ConnectResponse == nil {
		gql__input_ConnectResponse = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Pb_Input_ConnectResponse",
			Fields: graphql.InputObjectConfigFieldMap{
				"uri": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"account_id": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"user_id": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"temp_jwt_token": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__input_ConnectResponse
}

func Gql__input_ConnectRequest() *graphql.InputObject {
	if gql__input_ConnectRequest == nil {
		gql__input_ConnectRequest = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Pb_Input_ConnectRequest",
			Fields: graphql.InputObjectConfigFieldMap{
				"provider": &graphql.InputObjectFieldConfig{
					Type: Gql__enum_VCSConnectionProvider(),
				},
			},
		})
	}
	return gql__input_ConnectRequest
}

func Gql__input_AccountVCSConnection() *graphql.InputObject {
	if gql__input_AccountVCSConnection == nil {
		gql__input_AccountVCSConnection = graphql.NewInputObject(graphql.InputObjectConfig{
			Name: "Pb_Input_AccountVCSConnection",
			Fields: graphql.InputObjectConfigFieldMap{
				"id": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"provider": &graphql.InputObjectFieldConfig{
					Type: Gql__enum_VCSConnectionProvider(),
				},
				"account_id": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
			},
		})
	}
	return gql__input_AccountVCSConnection
}
