version: '3.3'

volumes:
  postgres:

services:

  backend_api:
    image: golang:1.16.4-stretch
    working_dir: /app
    volumes:
      - .:/app
      - /tmp/docker_cache/go_mod:/go/pkg/mod
    env_file:
      - envs/common.env
      - envs/api.env
    command: bin/goarcc
    depends_on:
      - postgres

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
