apiVersion: skaffold/v2beta16	# 	version of the configuration.
kind: Config	# 	always Config.


build:
  artifacts:
    - image: platform
      context: backend
      custom:    # 	beta builds images using a custom build script written by the user.
#        buildCommand: echo $IMAGE_TAG
        buildCommand: |-
          pack build $IMAGE_REPO \
              --tag $IMAGE \
              --path . \
              --buildpack gcr.io/paketo-buildpacks/go \
              --builder paketobuildpacks/builder:tiny \
              --volume "$(pwd)/../common:/common"
#  tagPolicy:
#    gitCommit:
#      variant: AbbrevTreeSha


deploy:
  helm:
    releases:
      - name: api
        chartPath: deployment/k8s/backend
        wait: true
