nameOverride: postgres
postgresqlPostgresPassword: postgres
postgresqlPassword: postgres
postgresqlDatabase: postgres

primary:
  tolerations:
    - key: durable
      operator: Equal
      value: "true"
      effect: NoSchedule

  nodeSelector:
    nodetype: durable