grpc:
    Port: 8080
    Host: localhost

graphql:
    Port: 8081
    Host: localhost

rest:
    Port: 8082
    Host: localhost

healthcheck:
    Port: 8083
    Host: localhost

promthesius:
    Port: 8084
    Host: localhost

logger:
    LogLevel: -1

postgres:
    PostgresqlHost: localhost
    PostgresqlPort: 5432
    PostgresqlUser: postgres
    PostgresqlPassword: root
    PostgresqlDbname: deqode
    PostgresqlSslmode: false
    PgDriver: pgx

metrics:
    Url: 0.0.0.0:7070
    ServiceName: AlfredMetrics

jaeger:
    Host: localhost
    Port: 6831
    ServiceName: AlfredTracing
    LogSpans: false
auth:
  Auth0ClientId    : BFnfdaibKSdqkSAOksr3XuUNJuCW9zbZ
  Auth0Domain      : alfred-sh.us.auth0.com
  Auth0ClientSecret: e6JJn1cKSEHk8p1FuoBdDbhmWWINevDitFBsWMTkZi8BbL8AVTQlLfgkwSCyyqJX
  Auth0CallbackUrl : http://localhost:8082/v1/authentication/callback
