grpc:
    port: 8000
    host: localhost
    request_timeout: 20

graphql:
    port: 8081
    host: localhost
    request_Timeout: 20

rest:
    port: 8082
    host: localhost
    request_timeout: 20

health_check:
    port: 8083
    host: localhost

promthesius:
    port: 8084
    host: localhost

logger:
    log_level: -1

postgres:
    host: localhost
    port: 5432
    user: atul
    password: atul
    db_name: alfred
    ssl_mode: true
    driver: pgx

metrics:
    url: 0.0.0.0:7070
    service_name: AlfredMetrics

jaeger:
    host: localhost
    port: 6831
    service_name: AlfredTracing
    log_spans: false

auth:
  auth0_client_id    : BFnfdaibKSdqkSAOksr3XuUNJuCW9zbZ
  auth0_domain      : alfred-sh.us.auth0.com
  auth0_client_secret: e6JJn1cKSEHk8p1FuoBdDbhmWWINevDitFBsWMTkZi8BbL8AVTQlLfgkwSCyyqJX
  auth0_call_back_url : http://localhost:3000/authentication/callback

github_vcs_config:
  name: github
  itype: 1
  provider: GITHUB
  url_Template: https://github.com/login/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type={response_type}&scope={scope}
  client_id: 34c9188e9de51cfd07aa
  redirect_uri: http://localhost:3000/authentication/github/callback
  scope: user%20gist%20repo%20repo_deployment%20repo_hook
  response_type: code
  client_secret: 1069dcdbae399023baf4fa7eacf6ec4bbd652e2a
