grpc:
    Port: 8000
    Host: localhost
    RequestTimeout: 20

graphql:
    Port: 8081
    Host: localhost
    RequestTimeout: 20

rest:
    Port: 8082
    Host: localhost
    RequestTimeout: 20

healthcheck:
    Port: 8083
    Host: localhost

promthesius:
    Port: 8084
    Host: localhost

logger:
    LogLevel: -1

postgres:
    PostgresqlHost: localhost
    PostgresqlPort: 5432
    PostgresqlUser: atul
    PostgresqlPassword: atul
    PostgresqlDbname: alfred
    PostgresqlSslmode: false
    PgDriver: pgx

metrics:
    Url: 0.0.0.0:7070
    ServiceName: AlfredMetrics

jaeger:
    Host: localhost
    Port: 6831
    ServiceName: AlfredTracing
    LogSpans: false
auth:
  Auth0ClientId    : BFnfdaibKSdqkSAOksr3XuUNJuCW9zbZ
  Auth0Domain      : alfred-sh.us.auth0.com
  Auth0ClientSecret: e6JJn1cKSEHk8p1FuoBdDbhmWWINevDitFBsWMTkZi8BbL8AVTQlLfgkwSCyyqJX
  Auth0CallbackUrl : http://localhost:3000/authentication/callback

githubVCSConfig:
  name: github
  itype: 1
  provider: GITHUB
  urlTemplate: https://github.com/login/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type={response_type}&scope={scope}
  clientid: 34c9188e9de51cfd07aa
  redirecturi: http://localhost:3000/authentication/github/callback
  scope: user%20gist%20repo%20repo_deployment%20repo_hook
  responsetype: code
  clientsecret: 1069dcdbae399023baf4fa7eacf6ec4bbd652e2a
