apiVersion: v1
kind: Service
metadata:
  name: {{ include "scylla.fullname" . }}
  labels:
    {{- include "scylla.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 7000
      targetPort: intra-node
      protocol: TCP
      name: intra-node
    - port: 7001
      targetPort: tls-intra-node
      protocol: TCP
      name: tls-intra-node
    - port: 7199
      targetPort: jmx
      protocol: TCP
      name: jmx
    - port: 9042
      targetPort: cql
      protocol: TCP
      name: cql
    - port: 9180
      targetPort: prometheus
      protocol: TCP
      name: prometheus

  selector:
    {{- include "scylla.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "scylla.fullname" . }}-headless
  labels:
    {{- include "scylla.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true

  ports:
    - port: 7000
      targetPort: intra-node
      protocol: TCP
      name: intra-node
    - port: 7001
      targetPort: tls-intra-node
      protocol: TCP
      name: tls-intra-node
    - port: 7199
      targetPort: jmx
      protocol: TCP
      name: jmx
    - port: 9042
      targetPort: cql
      protocol: TCP
      name: cql
    - port: 9180
      targetPort: prometheus
      protocol: TCP
      name: prometheus

  selector:
    {{- include "scylla.selectorLabels" . | nindent 4 }}
