// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// GitServiceClient is the client API for git service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GitServiceClient interface {
	//listRepository list all repository of user's account
	ListRepository(ctx context.Context, in *ListRepositoryRequest, opts ...grpc.CallOption) (*ListRepositoryResponse, error)
	GetRepository(ctx context.Context, in *GetRepositoryRequest, opts ...grpc.CallOption) (*Repository, error)
	CloneRepository(ctx context.Context, in *CloneRepositoryRequest, opts ...grpc.CallOption) (*CloneRepositoryResponse, error)
	GetCloningStatus(ctx context.Context, in *GetCloningStatusRequest, opts ...grpc.CallOption) (*GetCloningStatusResponse, error)
}

type gitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGitServiceClient(cc grpc.ClientConnInterface) GitServiceClient {
	return &gitServiceClient{cc}
}

func (c *gitServiceClient) ListRepository(ctx context.Context, in *ListRepositoryRequest, opts ...grpc.CallOption) (*ListRepositoryResponse, error) {
	out := new(ListRepositoryResponse)
	err := c.cc.Invoke(ctx, "/alfred.git.v1.git/listRepository", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) GetRepository(ctx context.Context, in *GetRepositoryRequest, opts ...grpc.CallOption) (*Repository, error) {
	out := new(Repository)
	err := c.cc.Invoke(ctx, "/alfred.git.v1.git/GetRepository", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) CloneRepository(ctx context.Context, in *CloneRepositoryRequest, opts ...grpc.CallOption) (*CloneRepositoryResponse, error) {
	out := new(CloneRepositoryResponse)
	err := c.cc.Invoke(ctx, "/alfred.git.v1.git/CloneRepository", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServiceClient) GetCloningStatus(ctx context.Context, in *GetCloningStatusRequest, opts ...grpc.CallOption) (*GetCloningStatusResponse, error) {
	out := new(GetCloningStatusResponse)
	err := c.cc.Invoke(ctx, "/alfred.git.v1.git/GetCloningStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GitServiceServer is the server API for git service.
// All implementations should embed UnimplementedGitServiceServer
// for forward compatibility
type GitServiceServer interface {
	//listRepository list all repository of user's account
	ListRepository(context.Context, *ListRepositoryRequest) (*ListRepositoryResponse, error)
	GetRepository(context.Context, *GetRepositoryRequest) (*Repository, error)
	CloneRepository(context.Context, *CloneRepositoryRequest) (*CloneRepositoryResponse, error)
	GetCloningStatus(context.Context, *GetCloningStatusRequest) (*GetCloningStatusResponse, error)
}

// UnimplementedGitServiceServer should be embedded to have forward compatible implementations.
type UnimplementedGitServiceServer struct {
}

func (UnimplementedGitServiceServer) ListRepository(context.Context, *ListRepositoryRequest) (*ListRepositoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRepository not implemented")
}
func (UnimplementedGitServiceServer) GetRepository(context.Context, *GetRepositoryRequest) (*Repository, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepository not implemented")
}
func (UnimplementedGitServiceServer) CloneRepository(context.Context, *CloneRepositoryRequest) (*CloneRepositoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloneRepository not implemented")
}
func (UnimplementedGitServiceServer) GetCloningStatus(context.Context, *GetCloningStatusRequest) (*GetCloningStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCloningStatus not implemented")
}

// UnsafeGitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GitServiceServer will
// result in compilation errors.
type UnsafeGitServiceServer interface {
	mustEmbedUnimplementedGitServiceServer()
}

func RegisterGitServiceServer(s *grpc.Server, srv GitServiceServer) {
	s.RegisterService(&_GitService_serviceDesc, srv)
}

func _GitService_ListRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).ListRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alfred.git.v1.git/ListRepository",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).ListRepository(ctx, req.(*ListRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_GetRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).GetRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alfred.git.v1.git/GetRepository",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).GetRepository(ctx, req.(*GetRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_CloneRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).CloneRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alfred.git.v1.git/CloneRepository",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).CloneRepository(ctx, req.(*CloneRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitService_GetCloningStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCloningStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServiceServer).GetCloningStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alfred.git.v1.git/GetCloningStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServiceServer).GetCloningStatus(ctx, req.(*GetCloningStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GitService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "alfred.git.v1.git",
	HandlerType: (*GitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "listRepository",
			Handler:    _GitService_ListRepository_Handler,
		},
		{
			MethodName: "GetRepository",
			Handler:    _GitService_GetRepository_Handler,
		},
		{
			MethodName: "CloneRepository",
			Handler:    _GitService_CloneRepository_Handler,
		},
		{
			MethodName: "GetCloningStatus",
			Handler:    _GitService_GetCloningStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "git-service.proto",
}
