apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $secretName, $secretValue := .Values.envs.secrets }}
  {{ $secretName }}: {{ $secretValue | toString | b64enc | quote }}
  {{- end }}
