apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: grpc
      protocol: TCP
      name: grpc

    - port: 8081
      targetPort: graphql
      protocol: TCP
      name: graphql

    - port: 8082
      targetPort: rest
      protocol: TCP
      name: rest

    - port: 8083
      targetPort: health
      protocol: TCP
      name: health

  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
