
v3_use_offset: true
#token_hmac_secret_key: "<YOUR-SECRET-STRING-HERE>"
token_jwks_public_endpoint: https://goarcc-sh.us.auth0.com/.well-known/jwks.json # TODO: Make this configurable for different environments

api_key: abc # TODO: Make this configurable for different environments, better move it out of file
engine: memory
log_level: debug
address: 0.0.0.0
port: 7070
internal_port: 9000
allowed_origins:
  - "*"

client_anonymous: true # Make this false so users can not connect without token
anonymous: true

health: true
admin: true
admin_password: password
admin_secret: secret
