#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

runFrontendPreCommit() {
  cd frontend || echo "frontend does not exists" || exit 1
  npm run lint
  npm run build
}

runBackendPreCommit() {
  cd backend || echo "backend does not exists" || exit 1
}

runAgentPreCommit() {
  cd agent || echo "agent does not exists" || exit 1
}

directoryHasCommittableChanges() {
  # shellcheck disable=SC2092
  output=`git status -s "$@"`

  if [ -z "$output" ]
  then
        # shellcheck disable=SC2145
        echo "$@ has no change"
        return 1
  else
        # shellcheck disable=SC2145
        echo "$@ has changes"
        return 0
  fi

}

directoryHasCommittableChanges 'frontend' && runFrontendPreCommit
#directoryHasCommittableChanges 'backend' 'common' && runFrontendPreCommit
#directoryHasCommittableChanges 'agent' 'common' && runFrontendPreCommit

exit 0