name: Backend GO CI

on:
  push:
    paths:
      - backend/**
      - .github/**
      - common
      - protos/backend
      - protos/agent

jobs:
  build:
    name: build binaries
    defaults:
      run:
        working-directory: ./backend

    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: go mod download
        run:  go mod download

      - name: Lint
        run: make run-linter

      - name: test
        run: make test


      - name: Test In Docker
        uses: sudo-bot/action-docker-compose@latest
        with:
          # https://docs.docker.com/compose/reference/overview/
          cli-args: run --rm backend_api make test

      - name: Upload coverage reports
        uses: actions/upload-artifact@v2
        with:
          name: backend-coverage
          retention-days: 5
          path: backend/cover/

      - name: build
        run: make build

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: backend-binaries
          retention-days: 5
          path: backend/bin/