name: Backend GO CI

on:
  push:
    paths:
      - backend/**
      - .github/**
      - common
      - protos/backend
      - protos/agent

jobs:
  build:
    name: Test Code
    defaults:
      run:
        working-directory: ./backend

    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-
          restore-keys: |
            ${{ runner.os }}-go-

      - name: go mod download
        run:  docker-compose run backend_api go mod download

      - name: Lint
        run: docker-compose run backend_api make run-linter

      - name: Test In Docker
        run: docker-compose run backend_api make test

      - name: Upload coverage reports
        uses: actions/upload-artifact@v2
        with:
          name: backend-coverage
          retention-days: 5
          path: backend/cover/

      - name: build
        run: docker-compose run backend_api make build

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: backend-binaries
          retention-days: 5
          path: backend/bin/

      - run: docker-compose down