name: Frontend NextJS CI

on:
  push:
    paths:
      - frontend/**
      - .github/**
jobs:
  build:
    defaults:
      run:
        working-directory: ./frontend

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install
      - run: npm run lint
      - run: npm test -- --coverage
      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v2
        with:
          name: Coverage Reports
          retention-days: 5
          path: frontend/coverage/
      - run: npm run build