name: Go

on:
  push:
    branches: [ development ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Get
      run: cd backend && go get 

    - name: Build
      run: cd backend && go build -v ./...

    - name: Test
      run: cd backend && go test -v ./...
      
    - name: Fmt 
      run: cd backend && go fmt ./...
