name: CI

on:
  push:
    branches:
      - main
      - boilerplate

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building docker
        run: docker-compose build
      - name: Start Docker Container
        shell: bash
        run: docker-compose run --rm code-analyser bash runTestCases.sh
