name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Get
        run: go get

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Fmt
        run: cd backend && go fmt ./...
