name: Backend GO CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Test Code
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: /tmp/docker_cache/go_mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-
          restore-keys: |
            ${{ runner.os }}-go-
      #      # In this step, this action saves a list of existing images,
      #      # the cache is created without them in the post run.
      #      # It also restores the cache if it exists.
      #      - uses: satackey/action-docker-layer-caching@v0.0.11
      #        # Ignore the failure of a step and avoid terminating the job.
      #        continue-on-error: true

      - name: go mod download
        run:  docker-compose run backend_api go mod download

      - name: Lint
        run: docker-compose run backend_api make run-linter

      - name: Test In Docker
        run: docker-compose run backend_api make test


      - name: build
        run: docker-compose run backend_api make build

      - run: docker-compose down
